---
title: "Testing"
author: "Yuxin"
date: "6/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Iso)
```

# Compute K power
## K = 10
```{r}
N <- 10000
K = 10
Y = rep(0, K)
Y_j = Y
power_10 = NULL
for (j in 1:100){
  Y_j[2] = 0.01 * j
  r1_j = Y_j[2] /1
  power_10[j] = ratio_power(Y_j, r1_j , 1, N, K, compute_pcombine, compute_power)
}
```

## K = 50
```{r}
K = 50
Y = rep(0, K)
Y_j = Y
power_50 = NULL
for (j in 1:100){
  Y_j[2] = 0.01 * j
  r1_j = Y_j[2] /1
  power_50[j] = ratio_power(Y_j, r1_j , 1, N, K, compute_pcombine, compute_power)
}
```

## K = 100
```{r}
K = 100
Y = rep(0, K)
Y_j = Y
power_100 = NULL
for (j in 1:100){
  Y_j[2] = 0.01 * j
  r1_j = Y_j[2] /1
  power_100[j] = ratio_power(Y_j, r1_j , 1, N, K, compute_pcombine, compute_power)
}
```

# Isotonic Regression
```{r}
x <- seq(0.01,1,0.01)
iso1 <- ufit(power_10, x, type = "b")
iso2 <- ufit(power_50, x, type = "b")
iso3 <- ufit(power_100, x, type = "b")
plot(x, power_10, type = "l", xlab = "r1_value", ylab = "power", main = "Isotonic Regression Plot")
lines(x, power_50)
lines(x, power_100)
lines(iso1, col="red")
lines(iso2, col="red")
lines(iso3, col="red")
```

# Scaling
```{r}
# Compute the running time
start.time = Sys.time()

N <- 10000
K <- 10
Y1 <- rep(0, K)
Y2 <- rep(0, K)
Y3 <- rep(0, K)
Y4 <- rep(0, K)
d <- 100
temp1 <- NULL
temp2 <- NULL
temp3 <- NULL
temp4 <- NULL
for (j in 1:d){
  Y1[2] <- Y1[2] + 1/d
  temp1[j] <- ratio_power(Y1, 0.01, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y2[2] <- Y2[2] + 2/d
  temp2[j] <- ratio_power(Y2, 0.01, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y3[2] <- Y3[2] + 1.5/d
  temp3[j] <- ratio_power(Y3, 0.01, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y4[2] <- Y4[2] + 1.2/d
  temp4[j] <- ratio_power(Y4, 0.01, 1, N, K, compute_pcombine, compute_power)
}


plot(seq(0.01,1,0.01), temp1, type = "l", xlab = "Y1_value", ylab = "Power")
lines(seq(0.02,2,0.02), temp2, type = "l", col = "red")
lines(seq(0.015,1.5,0.015), temp3, type = "l", col = "blue")
lines(seq(0.012,1.2,0.012), temp4, type = "l", col = "green")


end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```

# P-value
## K = 10
```{r}
start.time = Sys.time()

N <- 10000
K <- 10
Y11 <- rep(0, K)
d <- 100
temp11 <- NULL
temp12 <- NULL
temp13 <- NULL
temp14 <- NULL
for (j in 1:d){
  Y11[2] <- Y11[2] + 1/d
  temp11[j] <- ratio_power(Y11, 0.01, 1, N, K, compute_pcombine, compute_power)
  temp12[j] <- ratio_power(Y11, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "max")
  temp13[j] <- ratio_power(Y11, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "median")
  temp14[j] <- ratio_power(Y11, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "mean")
}

plot(seq(0.01,1,0.01), temp11, type = "l", xlab = "Y1_value", ylab = "Power")
lines(seq(0.01,1,0.01), temp12, type = "l", col = "red")
lines(seq(0.01,1,0.01), temp13, type = "l", col = "blue")
lines(seq(0.01,1,0.01), temp14, type = "l", col = "green")

end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```

## K = 50
```{r}
start.time = Sys.time()

N <- 10000
K <- 50
Y21 <- rep(0, K)
d <- 100
temp21 <- NULL
temp22 <- NULL
temp23 <- NULL
temp24 <- NULL
for (j in 1:d){
  Y21[2] <- Y21[2] + 1/d
  temp21[j] <- ratio_power(Y21, 0.01, 1, N, K, compute_pcombine, compute_power)
  temp22[j] <- ratio_power(Y21, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "max")
  temp23[j] <- ratio_power(Y21, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "median")
  temp24[j] <- ratio_power(Y21, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "mean")
}

plot(seq(0.01,1,0.01), temp21, type = "l", xlab = "Y1_value", ylab = "Power")
lines(seq(0.01,1,0.01), temp22, type = "l", col = "red")
lines(seq(0.01,1,0.01), temp23, type = "l", col = "blue")
lines(seq(0.01,1,0.01), temp24, type = "l", col = "green")

end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```


## K = 100
```{r}
start.time = Sys.time()

N <- 10000
K <- 100
Y31 <- rep(0, K)
d <- 100
temp31 <- NULL
temp32 <- NULL
temp33 <- NULL
temp34 <- NULL
for (j in 1:d){
  Y31[2] <- Y31[2] + 1/d
  temp31[j] <- ratio_power(Y31, 0.01, 1, N, K, compute_pcombine, compute_power)
  temp32[j] <- ratio_power(Y31, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "max")
  temp33[j] <- ratio_power(Y31, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "median")
  temp34[j] <- ratio_power(Y31, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "mean")
}

plot(seq(0.01,1,0.01), temp31, type = "l", xlab = "Y1_value", ylab = "Power")
lines(seq(0.01,1,0.01), temp32, type = "l", col = "red")
lines(seq(0.01,1,0.01), temp33, type = "l", col = "blue")
lines(seq(0.01,1,0.01), temp34, type = "l", col = "green")

end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```



# Scaling
# Scaling
## 1) fixing r1, check whether simultaneously changing Y1 and sig1 will change the power.
```{r}
# Compute the running time
start.time = Sys.time()

N <- 10000
K <- 10
Y1 <- rep(0, K)
Y2 <- rep(0, K)
Y3 <- rep(0, K)
Y4 <- rep(0, K)
d <- 100
temp1 <- NULL
temp2 <- NULL
temp3 <- NULL
temp4 <- NULL
for (j in 1:d){
  Y1[2] <- Y1[2] + 1/d
  temp1[j] <- ratio_power(Y1, 0.01, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y2[2] <- Y2[2] + 2/d
  temp2[j] <- ratio_power(Y2, 0.01, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y3[2] <- Y3[2] + 1.5/d
  temp3[j] <- ratio_power(Y3, 0.01, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y4[2] <- Y4[2] + 1.2/d
  temp4[j] <- ratio_power(Y4, 0.01, 1, N, K, compute_pcombine, compute_power)
}


plot(seq(0.01,1,0.01), temp1, type = "l", xlab = "Y1_value", ylab = "Power")
lines(seq(0.02,2,0.02), temp2, type = "l", col = "red")
lines(seq(0.015,1.5,0.015), temp3, type = "l", col = "blue")
lines(seq(0.012,1.2,0.012), temp4, type = "l", col = "green")


end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```

## 2) see different scaling Y1 and sigma1's ratio r1 
```{r}
N = 10000
K = 10
d = 100
# the scaled effective treatment 
Y_05 = rep(0, K)
Y_05[2] = 0.5

Y_1 = rep(0, K)
Y_1[2] = 1

Y_15 = rep(0, K)
Y_15[2] = 1.5 

Y_2 = rep(0, K)
Y_2[2] = 2

Y_25 = rep(0, K)
Y_25[2] = 2.5

# the respective power
ratio_05 = NULL
ratio_1 = NULL
ratio_15 = NULL
ratio_2 = NULL
ratio_25 = NULL

for (i in 1:d){
  ratio_05[i] = ratio_power(Y_05, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_1[i] = ratio_power(Y_1, i * 1/d, 1, N, K, compute_pcombine, compute_power)  
  ratio_15[i] = ratio_power(Y_15, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_2[i] = ratio_power(Y_2, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_25[i] = ratio_power(Y_25, i * 1/d, 1, N, K, compute_pcombine, compute_power)
}


plot(seq(1/d, 1, 1/d), ratio_05, type = "l", xlab = "r1_value", ylab = "Power", col = "aquamarine")
lines(seq(1/d, 1, 1/d), ratio_1, type = "l", col = "turquoise")
lines(seq(1/d, 1, 1/d), ratio_15, type = "l", col = "cornflowerblue")
lines(seq(1/d, 1, 1/d), ratio_2, type = "l", col = "deepskyblue")
lines(seq(1/d, 1, 1/d), ratio_25, type = "l", col = "navyblue")

legend("bottomright", c("Y = 0.5", "Y = 1", "Y = 1.5", "Y = 2", "Y = 2.5"), col = c("aquamarine", "Turquoise", "cornflowerblue", "deepskyblue", "navyblue"), lty=1)

```


# Increasing the total number N

```{r}
# setting the total number to be a hundred thousand
N = 100000
K = 10
d = 100
# the scaled effective treatment 
Y_05 = rep(0, K)
Y_05[2] = 0.5

Y_1 = rep(0, K)
Y_1[2] = 1

Y_15 = rep(0, K)
Y_15[2] = 1.5 

Y_2 = rep(0, K)
Y_2[2] = 2

Y_25 = rep(0, K)
Y_25[2] = 2.5

# the respective power
ratio_05 = NULL
ratio_1 = NULL
ratio_15 = NULL
ratio_2 = NULL
ratio_25 = NULL

for (i in 1:d){
  ratio_05[i] = ratio_power(Y_05, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_1[i] = ratio_power(Y_1, i * 1/d, 1, N, K, compute_pcombine, compute_power)  
  ratio_15[i] = ratio_power(Y_15, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_2[i] = ratio_power(Y_2, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_25[i] = ratio_power(Y_25, i * 1/d, 1, N, K, compute_pcombine, compute_power)
}


plot(seq(1/d, 1, 1/d), ratio_05, type = "l", xlab = "r1_value", ylab = "Power", col = "aquamarine", main = "Power pattern with different Yk level given total number N = 100000")
lines(seq(1/d, 1, 1/d), ratio_1, type = "l", col = "turquoise")
lines(seq(1/d, 1, 1/d), ratio_15, type = "l", col = "cornflowerblue")
lines(seq(1/d, 1, 1/d), ratio_2, type = "l", col = "deepskyblue")
lines(seq(1/d, 1, 1/d), ratio_25, type = "l", col = "navyblue")

legend("bottomright", c("Y = 0.5", "Y = 1", "Y = 1.5", "Y = 2", "Y = 2.5"), col = c("aquamarine", "Turquoise", "cornflowerblue", "deepskyblue", "navyblue"), lty=1)
```


```{r}
# setting the total number to be a hundred thousand
N = 1000
K = 10
d = 100
# the scaled effective treatment 
Y_05 = rep(0, K)
Y_05[2] = 0.5

Y_1 = rep(0, K)
Y_1[2] = 1

Y_15 = rep(0, K)
Y_15[2] = 1.5 

Y_2 = rep(0, K)
Y_2[2] = 2

Y_25 = rep(0, K)
Y_25[2] = 2.5

# the respective power
ratio_05 = NULL
ratio_1 = NULL
ratio_15 = NULL
ratio_2 = NULL
ratio_25 = NULL

for (i in 1:d){
  ratio_05[i] = ratio_power(Y_05, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_1[i] = ratio_power(Y_1, i * 1/d, 1, N, K, compute_pcombine, compute_power)  
  ratio_15[i] = ratio_power(Y_15, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_2[i] = ratio_power(Y_2, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_25[i] = ratio_power(Y_25, i * 1/d, 1, N, K, compute_pcombine, compute_power)
}


plot(seq(1/d, 1, 1/d), ratio_05, type = "l", xlab = "r1_value", ylab = "Power", col = "aquamarine", main = "Power pattern with different Yk level given total number N = 1000")
lines(seq(1/d, 1, 1/d), ratio_1, type = "l", col = "turquoise")
lines(seq(1/d, 1, 1/d), ratio_15, type = "l", col = "cornflowerblue")
lines(seq(1/d, 1, 1/d), ratio_2, type = "l", col = "deepskyblue")
lines(seq(1/d, 1, 1/d), ratio_25, type = "l", col = "navyblue")

legend("bottomright", c("Y = 0.5", "Y = 1", "Y = 1.5", "Y = 2", "Y = 2.5"), col = c("aquamarine", "Turquoise", "cornflowerblue", "deepskyblue", "navyblue"), lty=1)
```

```{r}
# setting the total number to be a hundred thousand
N = 50000
K = 10
d = 100
# the scaled effective treatment 
Y_05 = rep(0, K)
Y_05[2] = 0.5

Y_1 = rep(0, K)
Y_1[2] = 1

Y_15 = rep(0, K)
Y_15[2] = 1.5 

Y_2 = rep(0, K)
Y_2[2] = 2

Y_25 = rep(0, K)
Y_25[2] = 2.5

# the respective power
ratio_05 = NULL
ratio_1 = NULL
ratio_15 = NULL
ratio_2 = NULL
ratio_25 = NULL

for (i in 1:d){
  ratio_05[i] = ratio_power(Y_05, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_1[i] = ratio_power(Y_1, i * 1/d, 1, N, K, compute_pcombine, compute_power)  
  ratio_15[i] = ratio_power(Y_15, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_2[i] = ratio_power(Y_2, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_25[i] = ratio_power(Y_25, i * 1/d, 1, N, K, compute_pcombine, compute_power)
}


plot(seq(1/d, 1, 1/d), ratio_05, type = "l", xlab = "r1_value", ylab = "Power", col = "aquamarine", main = "Power pattern with different Yk level given total number N = 50000")
lines(seq(1/d, 1, 1/d), ratio_1, type = "l", col = "turquoise")
lines(seq(1/d, 1, 1/d), ratio_15, type = "l", col = "cornflowerblue")
lines(seq(1/d, 1, 1/d), ratio_2, type = "l", col = "deepskyblue")
lines(seq(1/d, 1, 1/d), ratio_25, type = "l", col = "navyblue")

legend("bottomright", c("Y = 0.5", "Y = 1", "Y = 1.5", "Y = 2", "Y = 2.5"), col = c("aquamarine", "Turquoise", "cornflowerblue", "deepskyblue", "navyblue"), lty=1)
```

```{r}
# setting the total number to be a hundred thousand
N = 500000
K = 10
d = 100
# the scaled effective treatment 
Y_05 = rep(0, K)
Y_05[2] = 0.5

Y_1 = rep(0, K)
Y_1[2] = 1

Y_15 = rep(0, K)
Y_15[2] = 1.5 

Y_2 = rep(0, K)
Y_2[2] = 2

Y_25 = rep(0, K)
Y_25[2] = 2.5

# the respective power
ratio_05 = NULL
ratio_1 = NULL
ratio_15 = NULL
ratio_2 = NULL
ratio_25 = NULL

for (i in 1:d){
  ratio_05[i] = ratio_power(Y_05, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_1[i] = ratio_power(Y_1, i * 1/d, 1, N, K, compute_pcombine, compute_power)  
  ratio_15[i] = ratio_power(Y_15, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_2[i] = ratio_power(Y_2, i * 1/d, 1, N, K, compute_pcombine, compute_power)
  ratio_25[i] = ratio_power(Y_25, i * 1/d, 1, N, K, compute_pcombine, compute_power)
}


plot(seq(1/d, 1, 1/d), ratio_05, type = "l", xlab = "r1_value", ylab = "Power", col = "aquamarine", main = "Power pattern with different Yk level given total number N = 500000")
lines(seq(1/d, 1, 1/d), ratio_1, type = "l", col = "turquoise")
lines(seq(1/d, 1, 1/d), ratio_15, type = "l", col = "cornflowerblue")
lines(seq(1/d, 1, 1/d), ratio_2, type = "l", col = "deepskyblue")
lines(seq(1/d, 1, 1/d), ratio_25, type = "l", col = "navyblue")

legend("bottomright", c("Y = 0.5", "Y = 1", "Y = 1.5", "Y = 2", "Y = 2.5"), col = c("aquamarine", "Turquoise", "cornflowerblue", "deepskyblue", "navyblue"), lty=1)
```















