---
title: "Multidimensional Effect Analysis"
author: "Xiaohui Li Yuxin Ma"
date: "6/17/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mvtnorm)
library(reshape2)
source("PvalueFunction.R")
source("RatioPower.R")
```

##Pre-test: distribution 
```{r}
# Number of units 
N = 10000
# Number of treatments
K = 10
# Y_0 Null Effect
Y_null = rep(0, K)
sigk = rep(1, K)

```



```{r}
p_comb_min = compute_pcombine(Yk, sigk, N, K,"min", 100)
hist(p_comb_min, breaks = 100)

p_comb_min2 = compute_pcombine(Yk, sigk, N, K,"min", 1000)
hist(p_comb_min2, breaks = 100)
```
```{r}
p_comb_mean = compute_pcombine(Yk, sigk, N, K,"mean", 10000)
hist(p_comb_mean, breaks = 100)
```

```{r}
p_comb_max = compute_pcombine(Yk, sigk, N, K,"max", 10000)
hist(p_comb_max, breaks = 100)
```

```{r}
p_comb_med = compute_pcombine(Yk, sigk, N, K,"median", 10000)
hist(p_comb_med, breaks = 100)
```


# N
```{r}
Yk = Y0 
Yk[2] = 0.1 

start.time = Sys.time()

p_cv = quantile(compute_pcombine(Y_null, sigk, N, K, ptype = "min", n = 10000 ), 0.05)

power_sample_100 = NULL
power_sample_1000 = NULL
power_sample_10000 = NULL

for (exp in 1:50){
  power_sample_100[exp] = compute_power(Yk, sigk, N, K, p_cv, R = 100)
  power_sample_1000[exp] = compute_power(Yk, sigk, N, K, p_cv, R = 1000)
  power_sample_10000[exp] = compute_power(Yk, sigk, N, K, p_cv, R = 10000)
}
hist(power_sample_100)
hist(power_sample_1000)
hist(power_sample_10000)

mean(power_sample_100)
mean(power_sample_1000)
mean(power_sample_10000)

var(power_sample_100)
var(power_sample_1000)
var(power_sample_10000)

end.time = Sys.time()
time.taken_binaryctratio = end.time - start.time
time.taken_binaryctratio

```


# N power
```{r}
K <- 10
d1 <- 10
d2 <- 5
power_min2 <- matrix(0, nrow = d2, ncol = d1)
power_med2 <- matrix(0, nrow = d2, ncol = d1)
power_men2 <- matrix(0, nrow = d2, ncol = d1)
for (i in 1:d2){
  Y <- rep(0, K)
  for (j in 1:d1){
  Y[2] <- Y[2] + 1/d1
  power_min2[i,j] = ratio_power(Y, 0.01, 1, N = 10^(i+1), K, compute_pcombine, compute_power, n = 1000, knum = 10)
  power_med2[i,j] = ratio_power(Y, 0.01, 1, N = 10^(i+1), K, compute_pcombine, compute_power, n = 1000, knum = 10, ptype = "median")
  power_men2[i,j] = ratio_power(Y, 0.01, 1, N = 10^(i+1), K, compute_pcombine, compute_power, n = 1000, knum = 10, ptype = "mean")
  }
}
par(mfrow=c(1,3))
plot(seq(0.1,1,0.1), power_min2[1,], type = "l", xlab = "Y1_value(min)", ylab = "power", col = 1, ylim = c(0,1))
lines(seq(0.1,1,0.1), power_min2[2,], type = "l", col = 2)
lines(seq(0.1,1,0.1), power_min2[3,], type = "l", col = 3)
lines(seq(0.1,1,0.1), power_min2[4,], type = "l", col = 4)
lines(seq(0.1,1,0.1), power_min2[5,], type = "l", col = 5)
plot(seq(0.1,1,0.1), power_men2[1,], type = "l", xlab = "Y1_value(mean)", ylab = "power", col = 1, ylim = c(0,1))
lines(seq(0.1,1,0.1), power_men2[2,], type = "l", col = 2)
lines(seq(0.1,1,0.1), power_men2[3,], type = "l", col = 3)
lines(seq(0.1,1,0.1), power_men2[4,], type = "l", col = 4)
lines(seq(0.1,1,0.1), power_men2[5,], type = "l", col = 5)
plot(seq(0.1,1,0.1), power_med2[1,], type = "l", xlab = "Y1_value(median)", ylab = "power", col = 1, ylim = c(0,1))
lines(seq(0.1,1,0.1), power_med2[2,], type = "l", col = 2)
lines(seq(0.1,1,0.1), power_med2[3,], type = "l", col = 3)
lines(seq(0.1,1,0.1), power_med2[4,], type = "l", col = 4)
lines(seq(0.1,1,0.1), power_med2[5,], type = "l", col = 5)
legend("topright", c("N=100", "N=1000", "N=10000", "N=100000", "N=1000000"), col = c(1,2,3,4,5), lty=1)
```


```{r}
power_mv_min <- NULL
power_mv_med <- NULL
power_mv_men <- NULL
for (i in 1:100){
 epsilon <- 0.01*i
 Ymv_temp <- rmvnorm(1, rep(0, K-1), diag(K-1))
 Ymv <- c(0, Ymv_temp)
 Ynorm <- Ymv * epsilon / sqrt(sum(Ymv^2))
 power_mv_min[i] <- ratio_power(Ynorm, Ynorm[2], 1, N, K, compute_pcombine, compute_power, knum = 10)
 power_mv_med[i] <- ratio_power(Ynorm, Ynorm[2], 1, N, K, compute_pcombine, compute_power, knum = 10, ptype = "median") 
 power_mv_men[i] <- ratio_power(Ynorm, Ynorm[2], 1, N, K, compute_pcombine, compute_power, knum = 10, ptype = "mean") 
}
plot(seq(0.01,1,0.01), power_mv_min, type = "l", xlab = "epsilon", ylab = "power", col = 1, ylim = c(0,1))
lines(seq(0.01,1,0.01), power_mv_med, type = "l", xlab = "epsilon", ylab = "power", col = 2, ylim = c(0,1))

```


```{r}
epsilon = 0.1
power_sample = NULL
p_cv = quantile(compute_pcombine(Y_null, sigk, N, K, ptype = "min", n = 10000 ), 0.05)

for (exp in 1:100){
  Y_1 = multi_y(epsilon, K)
  power_sample[exp] = compute_power(Y_1, sigk, N, K, p_cv, R = 100)
}

hist(power_sample)
var(power_sample)
mean(power_sample)
```

```{r}
power_sample =data.frame(power_sample = power_sample)
ggplot(power_sample, aes(x = power_sample)) + geom_histogram(fill = 'blue', alpha = 0.4, position = "identity") + ggtitle("Power histogram given fixed epsilon 0.1 with 100 repetition times") + annotate("text", x = 0.35, y = 10, label = "Variance is 0.00179")
```





```{r}
compute_binary_level(Y, sigk, N, K, delta = 0.005, p_cv = p_cv)
```


```{r}
delta = 0.005

level_eps = NULL

for (k in 2:100){
  Yk = rep(0, k)
  sigk = rep(1, k)
  p_cvk = p_cv = quantile(compute_pcombine(Yk, sigk, N, k, n = 10000 ), 0.05)
  level_eps[k] = compute_binary_level(Y, sigk, N, k, eps_ceil = 2, delta, p_cv = p_cvk)
} 

```

```{r}
level_eps = level_eps[-1]
k = seq(2,100,1)
fit = lm(level_eps ~ k)$fitted
summary(lm(level_eps ~ k))

data_eps = data.frame(eps = level_eps, k = k, fit = fit)
ggplot(data_eps) + geom_point(aes(x = k, y = eps, colour = eps), position = 'jitter') + geom_line(aes(x = k, y = fit)) + labs(x = "treatment size K", y ="critical epsilon") + ggtitle("Power curve of Min type given different total units number") + annotate("text", x = 80, y = 0.25, label = "R squared is 0.999")
```



#mean median case
```{r}
N = c(1000, 5000, 10000, 50000, 100000, 500000, 1000000)
n_level = 7
n_step = 100

K = 10
sigk = rep(1, K)
Yk = rep(0, K)

power_mean = matrix(0, nrow = n_level, ncol = n_step)
power_med = matrix(0, nrow = n_level, ncol = n_step)

for (r in 1:n_level){
  # setting the total unit
  N_i = N[r]
  p_cv_mean_r = quantile(compute_pcombine(Yk, sigk, N_i, K, ptype = "mean", n = 10000 ), 0.05)
  p_cv_med_r = quantile(compute_pcombine(Yk, sigk, N_i, K, ptype = "median", n = 10000 ), 0.05)
  for (i in 1:n_step){
    eps_i = i * 1/n_step
    
    # calculate the power by repetition
    power_mean_sample = NULL
    power_med_sample = NULL
    
    for (exp in 1:100){
      Y_1 = multi_y(eps_i, K)
      power_mean_sample[exp] = compute_power(Y_1, sigk, N_i, K, p_cv_mean_r, ptype = "mean", R = 1000)
      power_med_sample[exp] = compute_power(Y_1, sigk, N_i, K, p_cv_med_r, ptype = "median", R = 1000)
    }
    power_mean[r,i] = mean(power_mean_sample)
    power_med[r,i] = mean(power_med_sample)
  }
}

```


```{r}
data_mean = data.frame(t(power_mean), epsilon = seq(0.01,1,0.01))
colnames(data_mean) = c("N = 1000", "N = 5000", "N = 10000", "N = 50000", "N = 100000", "N = 500000", "N = 1000000", "epsilon")
data_mean = melt(data_mean, id = c("epsilon"))

```

```{r}
ggplot(data_mean, aes(x = epsilon, y = value, color = variable)) + geom_line() + labs(x = "epsilon value", y ="power") + ggtitle("Power curve of Mean type given different total units number")
```


```{r}
data_med = data.frame(t(power_med), epsilon = seq(0.01,1,0.01))
colnames(data_med) = c("N = 1000", "N = 5000", "N = 10000", "N = 50000", "N = 100000", "N = 500000", "N = 1000000", "epsilon")
data_med = melt(data_med, id = c("epsilon"))
```

```{r}
ggplot(data_med, aes(x = epsilon, y = value, color = variable)) + geom_line() + labs(x = "epsilon value", y ="power") + ggtitle("Power curve of Median type given different total units number")
```

```{r}
start.time = Sys.time()

n_step = 150

power_min = matrix(0, nrow = n_level, ncol = n_step)

for (r in 1:n_level){
  # setting the total unit
  N_i = N[r]
  p_cv_min_r = quantile(compute_pcombine(Yk, sigk, N_i, K, ptype = "min", n = 10000 ), 0.05)

  for (i in 1:n_step){
    eps_i = i * 1.5/n_step
    
    # calculate the power by repetition
    power_min_sample = NULL
    
    for (exp in 1:200){
      Y_1 = multi_y(eps_i, K)
      power_min_sample[exp] = compute_power(Y_1, sigk, N_i, K, p_cv_min_r, ptype = "min", R = 2000)
    }
    power_min[r,i] = mean(power_min_sample)
  }
}

end.time = Sys.time()
time.taken_binaryctratio = end.time - start.time
time.taken_binaryctratio
```

```{r}
data_min = data.frame(t(power_min), epsilon = seq(0.01,1.5,0.01))
colnames(data_min) = c("N = 1000", "N = 5000", "N = 10000", "N = 50000", "N = 100000", "N = 500000", "N = 1000000", "epsilon")
data_min = melt(data_min, id = c("epsilon"))
```

```{r}
ggplot(data_min, aes(x = epsilon, y = value, color = variable)) + geom_line() + scale_x_continuous(limits = c(0,1))  +labs(x = "epsilon value", y ="power") + ggtitle("Power curve of Minimal type given different total units number") 
```

```{r}
start.time = Sys.time()

N = c(1000, 5000, 10000, 50000, 100000, 500000, 1000000)
n_level = 7
n_step = 150

power_max = matrix(0, nrow = n_level, ncol = n_step)

for (r in 1:n_level){
  # setting the total unit
  N_i = N[r]
  p_cv_max_r = quantile(compute_pcombine(Yk, sigk, N_i, K, ptype = "max", n = 10000 ), 0.05)

  for (i in 1:n_step){
    eps_i = i * 1.5/n_step
    
    # calculate the power by repetition
    power_max_sample = NULL
    
    for (exp in 1:100){
      Y_1 = multi_y(eps_i, K)
      power_max_sample[exp] = compute_power(Y_1, sigk, N_i, K, p_cv_min_r, ptype = "max", R = 1000)
    }
    power_max[r,i] = mean(power_max_sample)
  }
}

end.time = Sys.time()
time.taken_binaryctratio = end.time - start.time
time.taken_binaryctratio
```

```{r}
data_max = data.frame(t(power_max), epsilon = seq(0.01,1.5,0.01))
colnames(data_max) = c("N = 1000", "N = 5000", "N = 10000", "N = 50000", "N = 100000", "N = 500000", "N = 1000000", "epsilon")
data_max = melt(data_max, id = c("epsilon"))
```

```{r}
ggplot(data_max, aes(x = epsilon, y = value, color = variable)) + geom_line() + scale_x_continuous(limits = c(0,1))  +labs(x = "epsilon value", y ="power") + ggtitle("Power curve of Maximal type given different total units number") 
```

```{r}
delta = 0.005

level_eps_med = NULL

for (k in 2:100){
  Yk = rep(0, k)
  sigk = rep(1, k)
  p_cvmed = quantile(compute_pcombine(Yk, sigk, N, k, ptype = "median", n = 10000 ), 0.05)
  level_eps_med[k] = compute_binary_level(Y, sigk, N, k, eps_start = 0, eps_ceil = 4, delta, p_cv = p_cvmed, eps_rep = 200, ptype = "median")
}

```

```{r}
plot(level_eps_men, type = "l")
lines(level_eps_med, col ="green")
lines(level_eps, col = "blue")
```




```{r}
level_eps_men = NULL

for (k in 2:100){
  Yk = rep(0, k)
  sigk = rep(1, k)
  p_cvmen = quantile(compute_pcombine(Yk, sigk, N, k, ptype = "mean", n = 10000 ), 0.05)
  level_eps_men[k] = compute_binary_level(Y, sigk, N, k, eps_start = 0, eps_ceil = 4, delta, p_cv = p_cvmen, eps_rep = 200, ptype = "mean")  
}
```






```{r}
eps = 0.1
power_med_k = NULL
power_men_k = NULL

eps_rep = 100

for (k in 2:100){
  Yk = rep(0, k)
  sigk = rep(1, k)
  
  p_cvmed = quantile(compute_pcombine(Yk, sigk, N, k, ptype = "median", n = 10000 ), 0.05)
  p_cvmen = quantile(compute_pcombine(Yk, sigk, N, k, ptype = "mean", n = 10000 ), 0.05)
  
  power_med_exp = NULL
  power_men_exp = NULL
    
  for (exp in 1:eps_rep){
    Y_e = multi_y(eps, k)
    power_med_exp[exp] = compute_power(Y_e, sigk, N, k, p_cvmed, ptype = "median", R = 2000)
    power_men_exp[exp] = compute_power(Y_e, sigk, N, k, p_cvmen, ptype = "mean", R = 2000)
  }
  
  power_med_k[k] = mean(power_med_exp)
  power_men_k[k] = mean(power_men_exp)
} 

```

```{r}
plot(power_med_k, type = "l", main = "Power of median type combined p-value against K size given epsion = 0.1", xlab = "K treatment size", ylab = "Power")
```

```{r}
plot(power_men_k, type = "l", main = "Power of mean type combined p-value against K size given epsion = 0.1", xlab = "K treatment size", ylab = "Power")
```

```{r}
start.time = Sys.time()
K_small = 2
K_large = 20

Yk_s = rep(0, K_small)
Yk_l = rep(0, K_large)

sigk_s = rep(1, K_small)
sigk_l = rep(1, K_large)

eps_step = 100

# power
power_min_eps_s = NULL
power_med_eps_s = NULL
power_men_eps_s = NULL

power_min_eps_l = NULL
power_med_eps_l = NULL
power_men_eps_l = NULL

# critical rejected p-value
p_cvmin_small = quantile(compute_pcombine(Yk_s, sigk_s, N, K_small, ptype = "min", n = 10000 ),0.05)
p_cvmed_small = quantile(compute_pcombine(Yk_s, sigk_s, N, K_small, ptype = "median", n = 10000 ),0.05)
p_cvmen_small = quantile(compute_pcombine(Yk_s, sigk_s, N, K_small, ptype = "mean", n = 10000 ), 0.05)
p_cvmin_large = quantile(compute_pcombine(Yk_l, sigk_l, N, K_large, ptype = "min", n = 10000 ),0.05)
p_cvmed_large = quantile(compute_pcombine(Yk_l, sigk_l, N, K_large, ptype = "median", n = 10000 ),0.05)
p_cvmen_large = quantile(compute_pcombine(Yk_l, sigk_l, N, K_large, ptype = "mean", n = 10000 ), 0.05)

for (i in 1:eps_step){
  eps_i = i*1/eps_step

  power_min_exp_s = NULL
  power_med_exp_s = NULL
  power_men_exp_s = NULL
  power_min_exp_l = NULL
  power_med_exp_l = NULL
  power_men_exp_l = NULL
    
  for (exp in 1:eps_rep){
    # small K case
    Y_e_small = multi_y(eps_i, K_small)

    power_min_exp_s[exp] = compute_power(Y_e_small, sigk_s, N, K_small, p_cvmin_small, ptype = "min", R = 2000)
    power_med_exp_s[exp] = compute_power(Y_e_small, sigk_s, N, K_small, p_cvmed_small, ptype = "median", R = 2000)
    power_men_exp_s[exp] = compute_power(Y_e_small, sigk_s, N, K_small, p_cvmen_small, ptype = "mean", R = 2000)
    
    # large K case
    Y_e_large = multi_y(eps_i, K_large)

    power_min_exp_l[exp] = compute_power(Y_e_large, sigk_l, N, K_large, p_cvmin_large, ptype = "min", R = 2000)
    power_med_exp_l[exp] = compute_power(Y_e_large, sigk_l, N, K_large, p_cvmed_large, ptype="median", R = 2000)
    power_men_exp_l[exp] = compute_power(Y_e_large, sigk_l, N, K_large, p_cvmen_large, ptype = "mean", R = 2000)
    
  }
  power_min_eps_s[i] = mean(power_med_exp_s)
  power_med_eps_s[i] = mean(power_med_exp_s)
  power_men_eps_s[i] = mean(power_men_exp_s)
  
  
  power_min_eps_l[i] = mean(power_med_exp_l)
  power_med_eps_l[i] = mean(power_med_exp_l)
  power_men_eps_l[i] = mean(power_men_exp_l)
}

end.time = Sys.time()
time.taken_binaryctratio = end.time - start.time
time.taken_binaryctratio
```


```{r}
plot(power_min_eps_l, type = "l")
plot(power_med_eps_l, col = "green")
plot(power_men_eps_l, col = "blue")
```

```{r}
eps_level = 0.1
N_step = 1000
K = 10
sigk = rep(0, K)



for (j in 1:100){
  N_j = 1000 * j
  for (exp in 1:eps_rep){
    power_min_exp =NULL
    power_med_exp = NULL
    power_men_exp = NULL
    
    Y_e = multi_y(eps_level, K)

    power_min_exp[exp] = compute_power(Y_e, sigk, N_j, K, p_cvmin_small, ptype = "min", R = 2000)
    power_med_exp[exp] = compute_power(Y_e, sigk, N_j, K, p_cvmed_small, ptype = "median", R = 2000)
    power_men_exp[exp] = compute_power(Y_e, sigk, N_j, K, p_cvmen_small, ptype = "mean", R = 2000)
  }
  
  power_min_N = mean(power_min_exp)
  power_med_N = mean(power_med_exp)
  power_men_N = mean(power_men_exp)
}

```


