---
title: "Testing"
author: "Yuxin"
date: "6/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Function of computing p-value
source("PvalueFunction.R")
# Function of computing power
source("RatioPower.R")
library(Iso)
```

# Compute K power
## K = 10
```{r}
N <- 10000
K = 10
Y = rep(0, K)
Y_j = Y
power_10 = NULL
for (j in 1:100){
  Y_j[2] = 0.01 * j
  r1_j = Y_j[2] /1
  power_10[j] = ratio_power(Y_j, r1_j , 1, N, K, compute_pcombine, compute_power)
}
```

## K = 50
```{r}
K = 50
Y = rep(0, K)
Y_j = Y
power_50 = NULL
for (j in 1:100){
  Y_j[2] = 0.01 * j
  r1_j = Y_j[2] /1
  power_50[j] = ratio_power(Y_j, r1_j , 1, N, K, compute_pcombine, compute_power)
}
```

## K = 100
```{r}
K = 100
Y = rep(0, K)
Y_j = Y
power_100 = NULL
for (j in 1:100){
  Y_j[2] = 0.01 * j
  r1_j = Y_j[2] /1
  power_100[j] = ratio_power(Y_j, r1_j , 1, N, K, compute_pcombine, compute_power)
}
```

# Isotonic Regression
```{r}
x <- seq(0.01,1,0.01)
iso1 <- ufit(power_10, x, type = "b")
iso2 <- ufit(power_50, x, type = "b")
iso3 <- ufit(power_100, x, type = "b")
plot(x, power_10, type = "l", xlab = "r1_value", ylab = "power", main = "Isotonic Regression Plot")
lines(x, power_50)
lines(x, power_100)
lines(iso1, col="red")
lines(iso2, col="red")
lines(iso3, col="red")
```

# Scaling
## r1 = 0.01
```{r}
# Compute the running time
start.time = Sys.time()

N <- 10000
K <- 10
Y10 <- rep(0, K)
Y20 <- rep(0, K)
Y30 <- rep(0, K)
Y40 <- rep(0, K)
d <- 100
temp10 <- NULL
temp20 <- NULL
temp30 <- NULL
temp40 <- NULL
for (j in 1:d){
  Y10[2] <- Y10[2] + 1/d
  temp10[j] <- ratio_power(Y10, 0.01, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y20[2] <- Y20[2] + 2/d
  temp20[j] <- ratio_power(Y20, 0.01, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y30[2] <- Y30[2] + 1.5/d
  temp30[j] <- ratio_power(Y30, 0.01, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y40[2] <- Y40[2] + 1.2/d
  temp40[j] <- ratio_power(Y40, 0.01, 1, N, K, compute_pcombine, compute_power)
}


plot(seq(0.01,1,0.01), temp10, type = "l", xlab = "Y1_value", ylab = "Power")
lines(seq(0.02,2,0.02), temp20, type = "l", col = "red")
lines(seq(0.015,1.5,0.015), temp30, type = "l", col = "blue")
lines(seq(0.012,1.2,0.012), temp40, type = "l", col = "green")
legend("bottomright", c("Y", "1.2Y", "1.5Y", "2Y"), col = c("black","green","blue","red"), lty=1)


end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```

# r1 change from 0.01 to 0.2
```{r}
# Compute the running time
start.time = Sys.time()

for (i in 1:20){
N <- 10000
K <- 10
Y1 <- rep(0, K)
Y2 <- rep(0, K)
Y3 <- rep(0, K)
Y4 <- rep(0, K)
d <- 100
temp1 <- matrix(0, ncol = 20, nrow = d)
temp2 <- matrix(0, ncol = 20, nrow = d)
temp3 <- matrix(0, ncol = 20, nrow = d)
temp4 <- matrix(0, ncol = 20, nrow = d)
for (j in 1:d){
  Y1[2] <- Y1[2] + 1/d
  temp1[j,i] <- ratio_power(Y1, 0.01*i, 1, N, K, compute_pcombine, compute_power)
  Y2[2] <- Y2[2] + 2/d
  temp2[j,i] <- ratio_power(Y2, 0.01*i, 1, N, K, compute_pcombine, compute_power)
  Y3[2] <- Y3[2] + 1.5/d
  temp3[j,i] <- ratio_power(Y3, 0.01*i, 1, N, K, compute_pcombine, compute_power)
  Y4[2] <- Y4[2] + 1.2/d
  temp4[j,i] <- ratio_power(Y4, 0.01*i, 1, N, K, compute_pcombine, compute_power)
}

#plot(seq(0.01,1,0.01), temp1[,i], type = "l", xlab = "Y1_value", ylab = "Power")
#lines(seq(0.02,2,0.02), temp2[,i], type = "l", col = "red")
#lines(seq(0.015,1.5,0.015), temp3[,i], type = "l", col = "blue")
#lines(seq(0.012,1.2,0.012), temp4[,i], type = "l", col = "green")
#legend("bottomright", c("Y", "1.2Y", "1.5Y", "2Y"), col = c("black","green","blue","red"), lty=1)
}




end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```




# r1 = 0.1
```{r}
# Compute the running time
start.time = Sys.time()

N <- 10000
K <- 10
Y1 <- rep(0, K)
Y2 <- rep(0, K)
Y3 <- rep(0, K)
Y4 <- rep(0, K)
d <- 100
temp1 <- NULL
temp2 <- NULL
temp3 <- NULL
temp4 <- NULL
for (j in 1:d){
  Y1[2] <- Y1[2] + 1/d
  temp1[j] <- ratio_power(Y1, 0.1, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y2[2] <- Y2[2] + 2/d
  temp2[j] <- ratio_power(Y2, 0.1, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y3[2] <- Y3[2] + 1.5/d
  temp3[j] <- ratio_power(Y3, 0.1, 1, N, K, compute_pcombine, compute_power)
}
for (j in 1:d){
  Y4[2] <- Y4[2] + 1.2/d
  temp4[j] <- ratio_power(Y4, 0.1, 1, N, K, compute_pcombine, compute_power)
}


plot(seq(0.01,1,0.01), temp1, type = "l", xlab = "Y1_value", ylab = "Power")
lines(seq(0.02,2,0.02), temp2, type = "l", col = "red")
lines(seq(0.015,1.5,0.015), temp3, type = "l", col = "blue")
lines(seq(0.012,1.2,0.012), temp4, type = "l", col = "green")
legend("bottomright", c("Y", "1.2Y", "1.5Y", "2Y"), col = c("black","green","blue","red"), lty=1)


end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```


# Fixed Y1
```{r}
Yt <- rep(0,K)
Yt[2] <- 0.01
d <- 100
value2 <- NULL
for (i in 1:d){
  value2[i] <- ratio_power(Yt, 0.01*i, 1, N, K, compute_pcombine, compute_power)
}
plot(seq(0.01,1,0.01), value2, type = "l", xlab = "r1_value", ylab = "Power")
```

```{r}
Yt <- rep(0,K)
Yt[2] <- 1
d <- 100
value1 <- NULL
for (i in 1:d){
  value1[i] <- ratio_power(Yt, 0.01*i, 1, N, K, compute_pcombine, compute_power)
}
plot(seq(0.01,1,0.01), value1, type = "l", xlab = "r1_value", ylab = "Power")
```


# P-value
## K = 10
a. fixed r1 value and varying Y1 & sigs
```{r}
start.time = Sys.time()

N <- 10000
K <- 10
Y11 <- rep(0, K)
d <- 100

temp11 <- NULL
temp12 <- NULL
temp13 <- NULL
temp14 <- NULL
for (j in 1:d){
  Y11[2] <- Y11[2] + 1/d
  temp11[j] <- ratio_power(Y11, 0.01, 1, N, K, compute_pcombine, compute_power, knum = 10)
  temp12[j] <- ratio_power(Y11, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "max", knum =10)
  temp13[j] <- ratio_power(Y11, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "median", knum =10)
  temp14[j] <- ratio_power(Y11, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "mean", knum = 10)
}

plot(seq(0.01,1,0.01), temp11, type = "l", xlab = "Y1_value", ylab = "Power" , main = "Power curve given different p-combined value type", col = "turquoise")
lines(seq(0.01,1,0.01), temp12, type = "l", col = "cornflowerblue")
lines(seq(0.01,1,0.01), temp13, type = "l", col = "deepskyblue")
lines(seq(0.01,1,0.01), temp14, type = "l", col = "navyblue")

legend("bottomright", c("Min ","Max", "Median", "Mean"), col = c("Turquoise","cornflowerblue", "deepskyblue", "navyblue"), lty=1)

end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```

b. fixed sigs value and varying r1 & Y1s
```{r}
N <- 10000
K = 10
Y41 = rep(0, K)
temp41 <- NULL
temp42 <- NULL
temp43 <- NULL
temp44 <- NULL
for (j in 1:200){
  Y41[2] = 0.01 * j
  r41 = Y41[2] / 1
  temp41[j] = ratio_power(Y41, r41, 1, N, K, compute_pcombine, compute_power, knum = 10)
  temp42[j] = ratio_power(Y41, r41, 1, N, K, compute_pcombine, compute_power, ptype = "max", knum = 10)
  temp43[j] = ratio_power(Y41, r41, 1, N, K, compute_pcombine, compute_power, ptype = "median", knum = 10)
  temp44[j] = ratio_power(Y41, r41, 1, N, K, compute_pcombine, compute_power, ptype = "mean", knum = 10)
}

plot(seq(0.01,1,0.01), temp41, type = "l", xlab = "r1_value", ylab = "Power",
main = "Power curve given different p-combined value type", col = "turquoise")
lines(seq(0.01,1,0.01), temp42, type = "l", col = "cornflowerblue")
lines(seq(0.01,1,0.01), temp43, type = "l", col = "deepskyblue")
lines(seq(0.01,1,0.01), temp44, type = "l", col = "navyblue")

legend("bottomright", c("Min ","Max", "Median", "Mean"), col = c("Turquoise","cornflowerblue", "deepskyblue", "navyblue"), lty=1)
```


## K = 2
a. fixed r1 and varying Y1 & sigs
```{r}
start.time = Sys.time()

N <- 10000
K <- 2
Y51 <- rep(0, K)
d <- 100
temp51 <- NULL
temp52 <- NULL
temp53 <- NULL
temp54 <- NULL
for (j in 1:d){
  Y51[2] <- Y51[2] + 1/d
  temp51[j] <- ratio_power(Y51, 0.01, 1, N, K, compute_pcombine, compute_power, knum = 10)
  temp52[j] <- ratio_power(Y51, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "max", knum = 10)
  temp53[j] <- ratio_power(Y51, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "median", knum = 10)
  temp54[j] <- ratio_power(Y51, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "mean", knum = 10)
}

plot(seq(0.01,1,0.01), temp51, type = "l", xlab = "Y1_value", ylab = "Power"
,main = "Power curve with different p-combined value type given K = 2", col = "turquoise")
lines(seq(0.01,1,0.01), temp52, type = "l", col = "cornflowerblue")
lines(seq(0.01,1,0.01), temp53, type = "l", col = "deepskyblue")
lines(seq(0.01,1,0.01), temp54, type = "l", col = "navyblue")

legend("bottomright", c("Min ","Max", "Median", "Mean"), col = c("Turquoise","cornflowerblue", "deepskyblue", "navyblue"), lty=1)
end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```


## K = 3
```{r}
start.time = Sys.time()

N <- 10000
K <- 3
Y61 <- rep(0, K)
d <- 100
temp61 <- NULL
temp62 <- NULL
temp63 <- NULL
temp64 <- NULL
for (j in 1:d){
  Y61[2] <- Y61[2] + 1/d
  temp61[j] <- ratio_power(Y61, 0.01, 1, N, K, compute_pcombine, compute_power)
  temp62[j] <- ratio_power(Y61, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "max")
  temp63[j] <- ratio_power(Y61, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "median")
  temp64[j] <- ratio_power(Y61, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "mean")
}

plot(seq(0.01,1,0.01), temp61, type = "l", xlab = "Y1_value", ylab = "Power",main = "Power curve with different p-combined value type given K = 2", col = "turquoise")
lines(seq(0.01,1,0.01), temp62, type = "l", col = "cornflowerblue")
lines(seq(0.01,1,0.01), temp63, type = "l", col = "deepskyblue")
lines(seq(0.01,1,0.01), temp64, type = "l", col = "navyblue")

legend("bottomright", c("Min ","Max", "Median", "Mean"), col = c("Turquoise","cornflowerblue", "deepskyblue", "navyblue"), lty=1)

end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```




## K = 50
```{r}
start.time = Sys.time()

N <- 10000
K <- 50
Y21 <- rep(0, K)
d <- 100
temp21 <- NULL
temp22 <- NULL
temp23 <- NULL
temp24 <- NULL
for (j in 1:d){
  Y21[2] <- Y21[2] + 1/d
  temp21[j] <- ratio_power(Y21, 0.01, 1, N, K, compute_pcombine, compute_power)
  temp22[j] <- ratio_power(Y21, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "max")
  temp23[j] <- ratio_power(Y21, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "median")
  temp24[j] <- ratio_power(Y21, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "mean")
}

plot(seq(0.01,1,0.01), temp21, type = "l", xlab = "Y1_value", ylab = "Power",main = "Power curve with different p-combined value type given K = 50", col = "turquoise")
lines(seq(0.01,1,0.01), temp22, type = "l", col = "cornflowerblue")
lines(seq(0.01,1,0.01), temp23, type = "l", col = "deepskyblue")
lines(seq(0.01,1,0.01), temp24, type = "l", col = "navyblue")

legend("bottomright", c("Min ","Max", "Median", "Mean"), col = c("Turquoise","cornflowerblue", "deepskyblue", "navyblue"), lty=1)

end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```


## K = 100
```{r}
start.time = Sys.time()

N <- 10000
K <- 100
Y31 <- rep(0, K)
d <- 100
temp31 <- NULL
temp32 <- NULL
temp33 <- NULL
temp34 <- NULL
for (j in 1:d){
  Y31[2] <- Y31[2] + 1/d
  temp31[j] <- ratio_power(Y31, 0.01, 1, N, K, compute_pcombine, compute_power)
  temp32[j] <- ratio_power(Y31, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "max")
  temp33[j] <- ratio_power(Y31, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "median")
  temp34[j] <- ratio_power(Y31, 0.01, 1, N, K, compute_pcombine, compute_power, ptype = "mean")
}

plot(seq(0.01,1,0.01), temp31, type = "l", xlab = "Y1_value", ylab = "Power", main = "Power curve with different p-combined value type given K = 100", col = "turquoise")
lines(seq(0.01,1,0.01), temp22, type = "l", col = "cornflowerblue")
lines(seq(0.01,1,0.01), temp23, type = "l", col = "deepskyblue")
lines(seq(0.01,1,0.01), temp24, type = "l", col = "navyblue")

legend("bottomright", c("Min ","Max", "Median", "Mean"), col = c("Turquoise","cornflowerblue", "deepskyblue", "navyblue"), lty=1)

end.time = Sys.time()
time.taken = end.time - start.time
time.taken
```


















