---
title: "Further Discussion"
author: "Xiaohui & Yuxin"
date: "05/31/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Call Function
```{r}
setwd("/Users/Viola/Desktop")
source("Function.R")
```

# Variable
```{r}
N = 10000
K = 10
Y = rep(0, K)
sig = rep(1, K)
d = 100 #alternative set number
```

# P-cv
```{r}
p_comb <- compute_pcombine(Y, sig, N, K)
p_cv <- quantile(p_comb, 0.05)
```

```{r}
Y_1 <- Y
Y_1[2] <- 0.9
sig_1 = rep(1, K)
compute_power(Y_1, sig_1, N, K, p_cv)
```


# Testing
```{r}
Y_1 <- Y
sig_1 <- sig
power_1 <- NULL
for (j in 1:d){
  Y_1[2] = Y_1[2] + 1/d #Generate new Y_k function
  power_1[j] <- compute_power(Y_1, sig_1, N, K, p_cv)
}
plot(seq(0.01,1,0.01), power_1, type = "l", xlab = "Y1_value", ylab = "Power")
abline(h = 0.8, col = "royalblue", lwd = 1)
abline(v = 0.573, col = "red", lwd = 1)
```

#Scaling (Multiply by 2 times)
```{r}
Y_2 <- Y
sig_2 <- rep(2, K)
power_2 <- NULL
for (j in 1:d){
  Y_2[2] = Y_2[2] + 2/d #Generate new Y_k function
  power_2[j] <- compute_power(Y_2, sig_2, N, K, p_cv)
}
plot(seq(0.02,2,0.02), power_2, type = "l", xlab = "Y1_value", ylab = "Power")
abline(h = 0.8, col = "royalblue", lwd = 1)
abline(v = 0.665, col = "red", lwd = 1)
```

# Example
```{r}
library(grDevices)
x <- 10*1:nrow(volcano)
y <- 10*1:ncol(volcano)
filled.contour(x, y, volcano, color = terrain.colors,xlab="Meters North",ylab="Meters West",main="The Topography of Maunga Whau",key.title = title(main="Height\n(meters)"))
mtext(paste("filled.contour(.) from", R.version.string),side = 1, line = 4, adj = 1, cex = .66)
```




```{r}
x <- 10*1:nrow(volcano)
y <- 10*1:ncol(volcano)
filled.contour(x, y, volcano, color = terrain.colors)
#,xlab="Meters North",ylab="Meters West",main="The Topography of Maunga Whau",key.title = #title(main="Height\n(meters)")
#mtext(paste("filled.contour(.) from", R.version.string),side = 1, line = 4, adj = 1, cex = .66)

power_t1 <- matrix(exp(rnorm(61*87)), ncol = 61, nrow = 87)
x <- 10*1:nrow(power_t1)
y <- 10*1:ncol(power_t1)
filled.contour(x, y, power_t1, color = terrain.colors)
```






















